### ISSUE TITLE
[Request]- short video toturial 

### ISSUE THREAD

**Issue by Zila-itc** [cesarsalesgomes/dna#188]
I whould appreciate for your great idea to get nestjs working together with Directus. but if you have a short videos toturial is more understand for the begining. e.g. blog news show case and how it work from nest with directus, db and front end. thanks you

**Comment by cesarsalesgomes** [comment]
Glad to read that and thanks for the suggestion @Zila-itc. The main idea was to use Directus like an ORM to Nestjs (possible with graphql-codegen), to better handle logic that Directus don't provide out of the box.

There is currently a route within the cats feature on Nest that exemplifies the entire flow using Directus.

The same applies to the React folder, with examples of fetching in the cats feature with React Query (React Query graphql-codegen was used)

Soon I will update the documentation development topic to simplify all the necessary sdks generation steps and facilitate the initial execution of the project.
