### ISSUE TITLE
Execute multiple queries in a transaction 

### ISSUE THREAD

**Issue by xu4wang** [cesarsalesgomes/dna#700]
Thanks for sharing the project, Nest and Directus are all my preferred platforms too!

I have an issue combining them together. 

For example, in real world scenarios, sometimes it's required to update different items in Directus in one API call, I want all those updates all successful, otherwise none of them should be executed.

I was thinking about "transaction... commit ... rollback" but I am not sure how to implement using directus API/SDK?

**Comment by cesarsalesgomes** [comment]
> Thanks for sharing the project, Nest and Directus are all my preferred platforms too!
> 
> I have an issue combining them together. 
> 
> For example, in real world scenarios, sometimes it's required to update different items in Directus in one API call, I want all those updates all successful, otherwise none of them should be executed.
> 
> I was thinking about "transaction... commit ... rollback" but I am not sure how to implement using directus API/SDK?
> 

Hey @xu4wang , thank you for collaborating with the project.

I also investigated with Directus the possibility of transactions, but without success.

Directus uses knex behind the scenes, which itself offers transactions, so i think there is a possibility. 

I had also thought of raw queries, but I believe that Directus also does not offer the functionality.

**Comment by xu4wang** [comment]
> Hey @xu4wang , thank you for collaborating with the project.
> 
> I also investigated with Directus the possibility of transactions, but without success.
> 
> Directus uses knex behind the scenes, which itself offers transactions, so i think there is a possibility.
> 
> I had also thought of raw queries, but I believe that Directus also does not offer the functionality.

Checked the directus source, I understand if we put the CRUD operations in one API call, for example when we update one item, we can:
1.  Change some fields of the item,
2.  Add more items into another collection via referring a relational filed of the item.

The above 1 and 2 will be executed in one transaction inside Directus.

I think it covers most of my cases.
